config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :project_users, only: %i[index create destroy]
    resources :bugs, only: %i[new create edit update show destroy] do
      resources :user_bugs, only: %i[create update destroy]
    end
  end

  root to: "home#index"
end

app/models/project.rb
# frozen_string_literal: true

# Project Model
class Project < ApplicationRecord
  validates :title, presence: true, length: { minimum: 2, maximum: 15 }, uniqueness: true
  has_and_belongs_to_many :users, -> { distinct }

  has_many :bugs, dependent: :destroy
  belongs_to :manager, class_name: :User, foreign_key: "manager_id"
  # has_many :users, class_name: "user", foreign_key: "user_id"
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Project Controller to add projects through a User
class ProjectsController < ApplicationController
  include ProjectsHelper
  before_action :set_project, only: %i[show edit update destroy]
  before_action :set_project_auth, only: %i[show edit update destroy]

  def index
    authorize Project
    @projects = if current_user.role == "sq"
        Project.all
      else
        current_user.projects
      end
  end

  def new
    authorize Project
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.create(project_params)
    if @project.save
      redirect_to projects_path
      flash[:notice] = "Project Created Successfully"
    else
      render :new
      flash[:alert] = "Somethig went wrong! Bug not created"
    end
    authorize @project
  end

  def show; end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to projects_path
      flash[:notice] = "Project Updated Successfully"
    else
      render :edit
      flash[:alert] = "Cant update project!"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project Destroyed Successfully"
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :manager_id)
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def set_project_auth
    authorize @project
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

# Project Helper
module ProjectsHelper
end

app/views/projects/_all_project.html.erb
 <tr>
      <td><%= project.title%></td>
      <td><%= project.description%></td>
      <td><%= link_to 'View' ,  project ,class: 'btn btn-dark' %></td>
      <% if current_user.role == 'manager' %>
      <td><%= link_to 'Edit' , edit_project_path(project) , class: 'btn btn-warning' %></td>
      <td><%= link_to 'Destroy' , project, method: :delete, data: { confirm: 'Are you Sure'}, class: 'btn btn-danger' %></td>
      <% end %>
</tr>

app/views/projects/_form.html.erb
  <br>
  <%= form_with model: project, local: true do |form| %>
    <%= form.hidden_field :manager_id, :value => current_user.id %>
    <div>
     <%= render :partial => "layouts/form_errors", :locals => { :model => project } %>
    </div>
    <div>
      <%= form.text_field :title, placeholder: :title, class: "form-control" %>
    </div>
    <br>
    <div>
      <%= form.text_field :description, placeholder: :description, class: "form-control" %>
    </div>
    <br>
    <div>
      <%= form.submit class: "btn btn-success" %>
    </div>
  <% end %>
  <%= link_to "Back", projects_path, class: "btn btn-secondary" %>

app/views/projects/_show_project_bugs.html.erb
    <tr>
      <td><%= bug.title %></td>
      <td><button class="btn btn-outline-danger"><%= bug.status %></button></td>
      <td><button class="btn btn-outline-success"><%= bug.bug_type %></button></td>
      <td><%= link_to "View", project_bug_path(@project.id, bug.id), class: "btn btn-secondary" %></td>
      <% if current_user.role == "sq" %>
        <td><%= link_to "Edit", edit_project_bug_path(@project.id, bug.id), class: "btn btn-warning" %></td>
        <td><%= button_to "Delete", project_bug_path(@project.id, bug.id), method: :delete, data: { confirm: "Are you Sure" }, class: "btn btn-danger" %></td>
      <% end %>
      <% if bug.image.attached? %>
      <td> <%= cl_image_tag bug.image.key, :width => 200, :height => 150 %></td>
      <% end %>
    </tr>

app/views/projects/edit.html.erb
<h1>Edit Project Details</h1>
<br>
<%= render :partial => 'form', :locals => {:project => @project  } %>

app/views/projects/index.html.erb
<h1>Projects Avaliable</h1>
<br>
<div class='float-right'>
<% if current_user.role == 'manager'%>
<%= link_to  "New Project", new_project_path, class: "btn btn-primary " %>
<% end %>
</div>
<br>
<table class="table table-striped ">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan='3'>Actions</th>
     </tr>
  </thead>
  <tbody>
  <%= render partial: 'all_project', collection: @projects, as: :project %>
   </tbody>
</table>

app/views/projects/new.html.erb
<h1>New Project </h1>
<%= render :partial => 'form', :locals => {:project => @project  } %>

app/views/projects/show.html.erb
  <h4>Project Details</h4>
  <div class='float-right'>
    <% if current_user.role == "manager" %>
    <%= link_to "Edit Details", edit_project_path(@project), class: "btn btn-warning" %>
    <% end %>
  </div>
  <table class="table table-striped ">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <tr>
       <td><%= @project.title %></td>
       <td><%= @project.description %></td>
      </tr>
    </tbody>
  </table>
  <div class='float-right'>
    <% if current_user.role == "manager" %>
      <%= link_to "Assign new user", project_project_users_path(@project), class: "btn btn-warning" %>
    <% end %>
  </div>
  <h5>Assigned Developer and SQ</h5>
  <table class="table table-striped ">
    <thead class="thead-dark">
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Role</th>
        <% if current_user.role == "manager" %>
          <th>Actions</th>
         <% end %>
      </tr>
    </thead>
    <tbody>
     <% if @project.users.count > 1 %>
        <%= render partial: "project_users/assigned_user", collection: @project.users, as: :user %>
     <% else %>
      <%= render 'layouts/no_record'%>
     <% end %>
    </tbody>
  </table>
<br>
<br>
<h5>Bugs</h5>
<table class="table ">
<div class = 'float-right'>
<% if current_user.role == "sq" and @project.users.find_by(id: current_user.id) %>
<%= link_to "ADD BUG", new_project_bug_path(@project.id), class: "btn btn-warning" %>
<% end %>
</div>
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Bug Type</th>
      <th colspan = '4'>Actions</th>
     </tr>
  </thead>
  <tbody>
  <% if @project.bugs.any? %>
 <%= render partial: "show_project_bugs", collection: @project.bugs, as: :bug %>
  <% else %>
      <%= render 'layouts/no_record'%>
     <% end %>
   </tbody>
</table>
  <%= link_to "Back", projects_path, class: "btn btn-secondary" %>