config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :project_users, only: %i[index create destroy]
    resources :bugs, only: %i[new create edit update show destroy] do
      resources :user_bugs, only: %i[create update destroy]
    end
  end

  root to: "home#index"
end

app/models/bug.rb
# frozen_string_literal: true

# Bug Model
class Bug < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_one_attached :image
  validates :deadline, presence: true
  validates :description, presence: true
  validates :status, presence: true
  validates :bug_type, presence: true


  validates :title, presence: true, length: { minimum: 2, maximum: 15 }
  enum status: { New: 0, started: 1, completed: 2, resolved: 3 }
  enum bug_type: { bug: 0, feature: 1 }

  validate :image_type
  validate :must_have_valid_future_date

  private

  def image_type
    if image.attached?
    return if image.content_type.in?(%w['image/jpeg image/png image/jpg'])
    
    end
  end

  def must_have_valid_future_date
    return if deadline.blank? || deadline > Time.zone.today

    errors.add(:deadline, 'date cannot be in past')
  end
end

app/controllers/bugs_controller.rb
# frozen_string_literal: true

# BUGS Controller to add Bugs to a project that has a specific manager
class BugsController < ApplicationController
  include BugsHelper
  before_action :set_project, only: %i[new create show edit update destroy]
  before_action :set_bug, only: %i[show edit update destroy]
  before_action :set_bug_auth, only: %i[edit update destroy]

  def new
    authorize Bug
    @bug = Bug.new
  end

  def create
    authorize Bug
    @bug = @project.bugs.new(project_params)

    if @bug.save
      redirect_to project_path(@project)
      flash[:notice] = "Bug Created Successfully"
    else
      render :new
      flash.now[:alert] = "Somethig went wrong! Bug not created"
    end
  end

  def show; end

  def edit; end

  def update
    if @bug.update(project_params)
      redirect_to project_path(params[:project_id])
      flash[:notice] = "Bug Updated Successfully"
    else
      render :edit
      flash.now[:alert] = "Cant update project!"
    end

  end

  def destroy
    if @bug.destroy
      flash[:notice] = "Bug Destroyed Successfully"
    end

    redirect_to project_path(@project)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_bug
    @bug = Bug.find(params[:id])
  end

  def set_bug_auth
    authorize @bug
  end

  def project_params
    params.require(:bug).permit(:title, :description, :status, :bug_type, :deadline, :user_id, :image)
  end
end

app/helpers/bugs_helper.rb
# frozen_string_literal: true

# Bugs Helper
module BugsHelper
end

app/views/bugs/_form.html.erb
<%= form_with model: [project, bug], local: true do |form| %>
    <%= form.hidden_field :user_id, :value => user %>
    <div>
      <%= render :partial => "layouts/form_errors", :locals => { :model => bug } %>
    </div>
    <div><%= form.file_field :image,   accept:  '.png,.jpg,.jpeg' %></div>
      <br>
    <div><%= form.text_field :title, placeholder: :title, class: "form-control" %></div>
      <br>
    <div><%= form.text_field :description, placeholder: :description, class: "form-control" %></div>
      <br>
    <% unless form_type == 'new'%><div><%= form.select :status, :collection => Bug.statuses.keys.to_a %></div><%end%>
      <br>
    <div><%= form.select :bug_type, :collection => Bug.bug_types.keys.to_a %></div>
      <br>
    <%= form.date_field :deadline %>
      <br>
      <br>
    <div  class = 'd-flex justify-content-between'>
      <%= form.submit class: "btn btn-success" %>
      <%= link_to "Back", project_path(params[:project_id]), class: "btn btn-secondary" %>
    </div>
<% end %>

app/views/bugs/edit.html.erb
 <h1>Edit Bug </h1>
 <br>
 <%= render :partial => 'form',
     :locals => {:project => @project,
                 :bug => @bug,
                 :user => current_user.id ,
                 :form_type => 'edit' } %>

 <%# <%= render 'form', :project => @project, :bug => @bug, :user => current_user.id, :form_type => 'edit' %> %>

app/views/bugs/new.html.erb
<h1>New Bug </h1>
<%= render :partial => 'form',
           :locals => {:project => @project,
           :bug => @bug,
           :user => current_user.id,
           :form_type => 'new' } %>

app/views/bugs/show.html.erb
  <h3> BUG Details </h3>
  <% if @bug.image.attached? %>
     <%= cl_image_tag @bug.image.key, :width=>850, :height=>500 %>
  <% end %>
  <table class="table table-striped ">
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Title</td>
        <td><%= @bug.title%></td>
      </tr>
      <tr>
        <td>Description</td>
        <td><%= @bug.description%></td>
      </tr>
      <tr>
        <td>Status</td>
        <td><%= @bug.status%></td>
      </tr>
      <tr>
        <td>Type</td>
        <td><%= @bug.bug_type%></td>
      </tr>
        <tr>
        <td>Deadline</td>
        <td><%= @bug.deadline%></td>
      </tr>
    </tbody>
  </table>
  <%= link_to  "Back", project_path(params[:project_id]), class: 'btn btn-dark' %>
    <br>
    <br>
  <% if current_user.developer? %>
    <% unless current_user.bugs.exists?(@bug.id)  %>
      <td><%= button_to "Assign to yourself" , project_bug_user_bugs_path(bug_id: @bug.id) ,  class: "btn btn-success" %></td>
    <% end %>
    <br>
    <br>
  <h4>Bugs already assiged to yourself</h4>
  <table class="table ">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Bug Type</th>
        <th colspan = '2'>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% current_user.bugs.each do |bug| %>
      <tr>
        <td><%= bug.status %></td>
        <td> <button type="button" class="btn btn-outline-success"><%= bug.status.capitalize()%></button></td>
        <td> <button type="button" class="btn btn-outline-danger"><%= bug.bug_type.capitalize()%></button></td>
        <td><%= button_to "Un Assign" , project_bug_user_bug_path(bug_id: bug.id), params: {bug_id: bug.id} ,method: :delete, data: { confirm: 'Are you Sure'}, class: "btn btn-danger" %></td>
        <% if bug.status != 'resolved' %>
          <td><%= button_to "Change Status",  project_bug_user_bug_path(bug_id: bug.id), method: :patch ,class: 'btn btn-warning' %></td>
        <% end %>
    <%end%>
    </tbody>
  </table>
  <% end %>