config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :project_users, only: %i[index create destroy]
    resources :bugs, only: %i[new create edit update show destroy] do
      resources :user_bugs, only: %i[create update destroy]
    end
  end

  root to: "home#index"
end

app/controllers/project_users_controller.rb
# frozen_string_literal: true

# Project User Controller
class ProjectUsersController < ApplicationController
  before_action :set_project, only: %i[create destroy]
  before_action :set_user, only: %i[create]

  def index
    authorize User, :all_users?
    @users = User.all
  end

  def create
    authorize @project, :assgin_user?
    if @project.users.exists?(params[:user_id])
      flash[:alert] = "User is already Assigned"
    else
      @project.users << @user
      flash[:notice] = "User Assigned Successfully"
    end
    redirect_to project_path(@project.id)
  end

  def destroy

    authorize @project, :unassgin_user?
    if @project.users.delete(params[:user_id])
      flash[:notice] = "User Deleted Successfully"
    else
      flash[:alert] = "Something went wrong"
    end
    redirect_to project_path(@project.id)
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/project_users_helper.rb
# frozen_string_literal: true

# Projects User Helper
module ProjectUsersHelper
end

app/views/project_users/_all_users.html.erb
  <% if user.role != 'manager' %>
    <tr>
      <td><%= user.first_name%></td>
      <td><%= user.last_name%></td>
      <td><%= user.email%></td>
      <td><%= user.role%></td>
      <td><%= button_to "ADD", project_project_users_path, method: :post, params: {user_id: user.id}, class: "btn btn-success" %> </td>
    </tr>
  <%end%>

app/views/project_users/_assigned_user.html.erb
  <% if user.role != 'manager' %>
    <tr>
       <td><%= user.first_name%></td>
       <td><%= user.last_name%></td>
       <td><%= user.email%></td>
       <td><%= user.role%></td>
       <% if current_user.role == 'manager'%>
       <td><%= button_to "Delete", project_project_user_path(project_id: params[:id]), params: {user_id: user.id} ,method: :delete, data: { confirm: 'Are you Sure'}, class: "btn btn-danger"%></td>
       <% end %>
    </tr>
  <%end%>

app/views/project_users/index.html.erb
  <br>
  <h3>All Dev and SQ</h3>
  <br>
  <div class='float-right'>
  </div>
    <table class="table table-striped ">
      <thead class="thead-dark">
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Role</th>
          <th>Actions</th>
        </tr>
      </thead>
    <tbody>
    <% if @users.any? %>
    <%= render partial: "all_users", collection: @users, as: :user %>
    <% else %>
      <%= render "layouts/no_record" %>
    <% end %>
   </tbody>
   </table>
   <br>