config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :projects do
    resources :project_users, only: %i[index create destroy]
    resources :bugs, only: %i[new create edit update show destroy] do
      resources :user_bugs, only: %i[create update destroy]
    end
  end

  root to: "home#index"
end

app/views/layouts/_alert.html.erb
  <% if notice %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= notice %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <%end%>

  <% if alert %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= alert %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <%end%>

app/views/layouts/_form_errors.html.erb
  <% if model.errors.any? %>
     <% model.errors.full_messages.each do |message| %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
         </div>
    <% end %>
  <% end %>

app/views/layouts/_header_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'BUGZILLA', root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
     <% if user_signed_in? %>

       <li class="nav-item">
      <%= link_to  "Show Project", projects_path, class: 'nav-link' %>
      </li>
      <%# <li class="nav-item">
        <a class="nav-link" href="#">No table</a>
      </li> %>

     <%end%>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <ul class="navbar-nav mr-auto">
      <% if !user_signed_in? %>
      <li class="nav-item">
      <%= link_to  "Sign up", new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
       <%= link_to  "Login", new_user_session_path, class: 'nav-link' %>
      </li>
      <% else %>
      <li class= "nav-item">
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link"%>
      </li>
      <% end %>


    </ul>
    </form>
  </div>
</nav>

app/views/layouts/_no_record.html.erb
<tr>
  <td colspan='100%'><p class='text-center'>No Record Avaliable</p></td>
</tr>

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>BUGZILLA</title>
  </head>
  <body>
    <%= render 'layouts/header_bar'%>
     <div class = 'container'>
    <%= render 'layouts/alert'%>
     <%= yield %> </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>